### PR TITLE
Joe/feat/placeholder components

### PR DESCRIPTION
**Pull request by JoeDodgson**
## Summary of changes:
* Amended the repo folder structure so each page sits in its own folder within pages folder in the components folder:
image

* Created placeholder page components along with SCSS and CSS files for each of the remaining required pages for the MVP. Each contains static dummy content, some with buttons. Each of these page components will need to be developed much more individually

* Set up routing to placeholder components

* Moved static images into a static / images folder in src

* Amended existing SASS files to remove unnecessary mixins, e.g. $center: center

* Changed the use of AuthProvider (auth context provider) so that it only wraps around page components which we want to restrict access to, i.e. not Login or Register pages.

## Reviewer needs to:
* Run the app locally (front end and back end)

* Before logging in, check access is restricted to all routes, except Login and Register

* Log in, then check that something loads at each of the file paths (/login, /register, /project / project/:projectID/new-risk, etc.) See App.js for file paths

* Check 1 page component has been created for each required page

* Check routing is set up correctly (in App.js)

If you have any questions, let me know!

### CODE REVIEW

**Comment by meeday** [comment]
userform needs to be imported using new folder names and structure in app.js

**Comment by meeday** [comment]
The styling for the userform needs to be imported with the new file name

**Comment by JoeDodgson** [comment]
> userform needs to be imported using new folder names and structure in app.js

UserForm is imported in App.js on line 6
`import UserForm from "./components/UserForm/UserForm";`
and is then used on /logout and /register routes

**Comment by JoeDodgson** [comment]
> The styling for the userform needs to be imported with the new file name

UserForm.css is imported in UserForm.js on line 4
`import "./styles/UserForm.css";`

**Review by meeday — APPROVED** [review]

**Pull request merged**
